<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AeroBot.AvatarTester</AssemblyName>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath>.\..\..\Build\Data\Plugins</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Description>In-game preview and test of Silkroad avatars</Description>
    <Copyright>Copyright © 2026, RSBot Team</Copyright>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library\RSBot.Core\RSBot.Core.csproj" />
    <ProjectReference Include="..\..\SDUI\SDUI\SDUI.csproj" />
  </ItemGroup>

</Project>
